version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=Zf8mgdgTrjCUAfu0vyCSpkBJB6rK9qY8 # Generate this using 'php artisan key:generate'
      - DB_CONNECTION=mysql # Or your database connection
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_DATABASE=ddsbe1
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    depends_on:
      - mysql # Or your database service

  mysql: # Or your database service name
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: